### ISSUE TITLE
The Company changes

### ISSUE THREAD

**Issue by xAkShadow** [WSS-tracking/WSS#100]
Hey, here's the request to change The Company's to Paradigm Inc. 

New base location: Dizzy's Club (Yes I have Juli's permission) THE NEW BASE IS ON ANAL'S MAPPING SERVER (Paradigm-Inc-Base)
![image](https://user-images.githubusercontent.com/71608330/93720517-77f32d80-fb81-11ea-8ebd-3d9e68e70e2e.png)
![image](https://user-images.githubusercontent.com/71608330/93725961-41320d00-fbab-11ea-8742-2708e4b2ab57.png)
Color code: #4b0082 (can be the same for vehicles)
Skin ID: 124

We also have extra 100 Deagle, 150 Tec-9, an Admiral and an Infernus at the ThC spawn.

Thanks, have a great day!

**Comment by dev-bas** [comment]
Sorted. Ask lidl or zzenom how to fix the scaling issues (like the carpet).
