### ISSUE TITLE
Reward request (888's spawn)

### ISSUE THREAD

**Issue by Julian421** [WSS-tracking/WSS#103]
Request to add a spawn for 888's

Position: 2813.5358886719,-1186.04296875,26.06875038147
Skin ID: 285
Name: Unit888

**Comment by dev-bas** [comment]
Please provide me with a color code and a description to add for the spawnscreen.

**Comment by Julian421** [comment]
PositionX: 2813.5358886719
PositionY: -1186.04296875
PositionZ: 26.06875038147
Weapon ID: 3,23,17
Skin ID: 285
Name: Unit888
Colorcode: #0505aa
Crewpanel: unit888

**Comment by dev-bas** [comment]
Spawn added. Have fun with it!

**Comment by Liyones** [comment]
test
