### ISSUE TITLE
Cop / Desert Storm Taser

### ISSUE THREAD

**Issue by Liyones** [WSS-tracking/WSS#104]
Well when a cop/DS member tase someone and get nighstick instead he lose the taser for ever and he have to just respawn to get new one.[BUG]

**Comment by dev-bas** [comment]
I can't repoduce the situation you are describing. I spawned DS and tased someone, still had my taser after he stood up again. Be more descriptive please

**Comment by Liyones** [comment]
maybe got the point , before there was 2 SoA members i tased one of them and the other one killed me when i respawned at hospital i didn't got my taser.

**Comment by dev-bas** [comment]
Tried what you described with xakshadow and Ahron. Couldn't reproduce. Please report again when you have a video about it. Thanks!
