### ISSUE TITLE
[SPAWN] Bushido

### ISSUE THREAD

**Issue by xAkShadow** [WSS-tracking/WSS#107]
Name of spawn: Bushido
Position: 1641.8480224609,-1844.5550537109,13.54178237915
Skin ID: 170
Colorcode: #480808
Weapons: 5
Description (for spawnscreen: Bushido is a japanese underground racing group originally from the japanese streets.

**Comment by dev-bas** [comment]
Has been dealt with. Have fun with your spawn!
