### ISSUE TITLE
[SPAWN] North Coast Cartel

### ISSUE THREAD

**Issue by Liyones** [WSS-tracking/WSS#108]
Name of spawn: North Coast Cartel
Name in panel*: north_coast_cartl
Position: 1149.173828125,1210.6791992188,12.024182319641
Skin ID: 120
Colorcode: #333333
Weapons: 22.100
Description (for spawnscreen: North Coast Castel

*groups can ignore this one.

**Comment by dev-bas** [comment]
Added the spawn. Have fun with it guys.
