### ISSUE TITLE
[SPAWN] <Small D Racing> 

### ISSUE THREAD

**Issue by ItsAliceBiatch** [WSS-tracking/WSS#109]
Name of spawn: Small D Racing
Name in panel*: Small D Racing
Position: [do /getpos] 1652.4523925781,2197.6447753906,10.8203125
Skin ID: [skins to be added] 298
Colorcode: [hex or rgb] #FF007F
Weapons: [squads: 3.1,23.1000,17.10] [gangs: 22.100] [civilian groups: 2 / 5 / 6 / 7 / 10 / 11/ 12 / 15]
Description (for spawnscreen:

*groups can ignore this one.

**Comment by dev-bas** [comment]
Spawn added, have fun with it :)
