### ISSUE TITLE
North Coast Cartel Crew Reward

### ISSUE THREAD

**Issue by BigJoe3411** [WSS-tracking/WSS#111]
What are you requesting?: 
150 Tec-9 
250 AK-47 
100 Combat Shotgun
ModedSkin

Name of your gangpanel (Not needed for RP groups):  North Coast Cartl

Name of your group: North Costa Cartel

Name of your class: Leader

Description in Spawn Window:

Colorcode: #333333

Skin ID: 120

Weapon ID:  30,25,32

Spawn Location : 1146.5045166016,1210.4547119141,12.024785995483
[243072-technician-gtasa_manual.zip](https://github.com/WSS-tracking/WSS/files/5361552/243072-technician-gtasa_manual.zip)

Additional Info:

**Comment by dev-bas** [comment]
I've added the weapons. @zZenom or @WSSLidl please add the skin :)

**Comment by zZenom** [comment]
Skin is denied due to filesize, does a skin really need to be 34mb?!

**Comment by BigJoe3411** [comment]
https://easyupload.io/vuq69s   New skin 2MB  @WSSLidl  @zZenom

**Comment by zZenom** [comment]
Skin added.
