### ISSUE TITLE
[Crew Management] <North Coast Cartel Crew Rewards> 

### ISSUE THREAD

**Issue by BigJoe3411** [WSS-tracking/WSS#114]
What are you requesting?: Weapons and Car repair.

Name of your gangpanel (Not needed for RP groups): North_Coast_Cartl

Name of your group: North Coast Cartel

Name of your class:North Coast Cartel

Colorcode: #333333

Skin ID: 120

Weapon ID: 34 Sniper x2 (40 Bullets)

Cost 12.000.000$

**Comment by dev-bas** [comment]
40 sniper ammo added. You did not request or pay for the car repair script so you're not recieving that.  If you want it, you should request it at the crew reward topic at wssrpg.co.uk. Thanks!
