### ISSUE TITLE
[SPAWN] <Generation-X> Request

### ISSUE THREAD

**Issue by Alien3579** [WSS-tracking/WSS#115]
Name of spawn: Generation-X
Name in panel*: b-15
Position: [do /getpos]  2851.6958007813,1290.8553466797,11.390625
Skin ID: [skins to be added] 107
Colorcode: [hex or rgb] 0 97 7
Weapons: ] [gangs: 22.100] 
Description (for spawnscreen): Generation-X

**Comment by zZenom** [comment]
Spawn added.
