### ISSUE TITLE
[SPAWN] <The Coca-Cola Company> 

### ISSUE THREAD

**Issue by FekkOffItsHamppe** [WSS-tracking/WSS#116]
Name of spawn: The Coca-Cola Company
Name in panel*: 
Position:  -50.14693069458,-269.36428833008,6.633186340332
Skin ID: ]  241
Colorcode: #FF0000.
Weapons: 
Description (for spawnscreen: More than Cola. 

*groups can ignore this one.

**Comment by dev-bas** [comment]
@FekkOffItsHamppe Thanks for requesting the spawn, however, the color you've provided is too similar to the WSS staff color. Please propose a different one. Thanks!

**Comment by FekkOffItsHamppe** [comment]
#F76666

**Comment by dev-bas** [comment]
Added your spawn, but the XYZ needs to be reconfigured as it spawns you somewhere in a farm. Regardless of that, have fun with it ;p
