### ISSUE TITLE
[SPAWN] Nomad Motorcycle Club - Second Spawn 

### ISSUE THREAD

**Issue by NomadSmoke** [WSS-tracking/WSS#119]
Name of spawn: Nomad Motorcycle Club
Name in panel*: Nomad.Motorcycle.Club
Position: [do /getpos] -- The Map will need to be added in order to do /getpos in game, as it's behind a wall.
Skin ID: [skins to be added] 15 
Colorcode: [hex or rgb] HEX: #d4af37 /RGB: 212,175,55
Weapons: [squads: 3.1,23.1000,17.10] [gangs: 22.100] [civilian groups: 2 / 5 / 6 / 7 / 10 / 11/ 12 / 15] -- Note here because I will request more weapons now.
Description (for spawnscreen: Nomad Motorcycle Club, Don't live on your knees, Die on your feet.

(This spawn is the secondary that Nomad won at gangwars, we're still keeping the Red County Base for now until we have mapped Los Santos Docks)

I've attached the base files, the converted lua file, the original map file and the removals.

*groups can ignore this one.

**Comment by NomadSmoke** [comment]
[NomadBaseAndRemovals.zip](https://github.com/WSS-tracking/WSS/files/5398111/NomadBaseAndRemovals.zip)

**Comment by zZenom** [comment]
Sorry I've only just seen this and it's pretty late, if it's not added by tomorrow I'll do it after work <3

**Comment by dev-bas** [comment]
@NomadSmoke will convert the removalmap to lua and send the file back for upload. Other than that, this request is dealth with.
