### ISSUE TITLE
Bushido's Mapped Base Request

### ISSUE THREAD

**Issue by xAkShadow** [WSS-tracking/WSS#120]
The base is already (solved by Bas) in but some things remain to be changed, if possible:
* Move the current cars positions from: https://i.imgur.com/MbAGFLw.png to: https://i.imgur.com/BsnS6SE.png
* Change spawn location to: 1647.7608642578,-1817.1650390625,13.534378051758
* Move the firefighter spawn: https://i.imgur.com/z8tVRCY.png
* A disk if possible at: 1643.6284179688,-1817.2701416016,13.531518936157

Thanks for reading!

**Comment by dev-bas** [comment]
Consider it done, have fun with it guys :)
