### ISSUE TITLE
Nomad MC Reward Request

### ISSUE THREAD

**Issue by Hunterrino** [WSS-tracking/WSS#121]
What are you requesting?: Weapons, mechanic job.

Name of your gangpanel (Not needed for RP groups): Nomad.Motorcycle.Club

Name of your group: Nomad Motorcycle Club

Name of your class: Nomad Motorcycle Club

Colorcode:  #d4af37

Skin ID: 15

Weapon ID: 60 sniper (id 34) , 100 Sawn Off (id 26) , 500 M4(id 31) ,150 Tec (id 32)
also we're changing our cane to dildo (id 10)

**Comment by dev-bas** [comment]
Request processed. Have fun with it !
