### ISSUE TITLE
[SUGGESTION] <Increase arrest reward> 

### ISSUE THREAD

**Issue by FekkOffItsHamppe** [WSS-tracking/WSS#122]
Increase arrest reward would be nice. I arrested 4 guys earlier and got 45k and they all had 40+ stars

**Comment by WSSLidl** [comment]
So what is your suggestion, what would you wanna earn?

**Comment by FekkOffItsHamppe** [comment]
Somewhere between 35-50k would be fair

**Comment by WSSLidl** [comment]
It's 45k so what's the problem???

**Comment by FekkOffItsHamppe** [comment]
No it is not. 

https://imgur.com/a/hLFsN3l 

There you have a screenshot when Smoke arresting me having 48 stars. You can see how much he gets. 15.600$

**Comment by WSSLidl** [comment]
Consider it done
