### ISSUE TITLE
[Mapped Base+ spawn change] <Generation-X> 

### ISSUE THREAD

**Issue by Alien3579** [WSS-tracking/WSS#124]
Name of spawn: Generation-X
Name in panel*: b-15
Position: [do /getpos] Need to after the map is added
Skin ID: [skins to be added] 107
Colorcode: [hex or rgb] 0 97 7
Weapons: [gangs: 22.100] 
Description (for spawnscreen): Generation-X
Map: 
[XbaseSF.zip](https://github.com/WSS-tracking/WSS/files/5469304/XbaseSF.zip)

*groups can ignore this one.

**Comment by dev-bas** [comment]
Added. Have fun with it :)
