### ISSUE TITLE
[Spawn Change] <Unit 888> 

### ISSUE THREAD

**Issue by FekkOffItsHamppe** [WSS-tracking/WSS#125]
Name of spawn: Unit 888
Name in panel*: unit888
Position:  1122.7091064453,-2037.0187988281,69.894248962402
Skin ID: 285
Colorcode: [hex or rgb] #66ffff
Weapons: Same as the current spawn + 80 ammo
Description (for spawnscreen: Fuck Criminals, do the right join us. 

*groups can ignore this one.

**Comment by dev-bas** [comment]
Solved, have fun with it
