### ISSUE TITLE
[SUGGESTION] Nomad MC Base Bug Fixes and Gate.

### ISSUE THREAD

**Issue by NomadSmoke** [WSS-tracking/WSS#126]
We made a bit of an error with our mapping at LVX, we made an entrance SO big that we couldn't fit an object inside it, No object would fit :D 
So I'm uploading the same bug fixed base here. It's the same size, Just fixed to make a gate fit.
And this is the gate coords and the object ID. 

X:  1577.9000244141  Y: 713.16497802734  Z:  11.300000190735     -- Gate Closed -- 
X:  1577.9000244141  Y: 713.16497802734  Z:  7    -- Gate open--

Model of the gate: 9625 

Obviously, Locked to Nomad.Motorcycle.Club.
[nomadlvxbugfixed.zip](https://github.com/WSS-tracking/WSS/files/5493572/nomadlvxbugfixed.zip)

**Comment by dev-bas** [comment]
Solved, have fun with it.
