### ISSUE TITLE
Hamppe would like to have trucker delivery markers right there like old times

### ISSUE THREAD

**Issue by WSS-tracking** [WSS-tracking/WSS#16]
As reported on 22nd of August 2020: And this delivery on the old wss was worth, 37k, maybe you could do it again?

![afbeelding](https://user-images.githubusercontent.com/70011829/90965970-8809e580-e4cd-11ea-9be9-c110452edf2d.png)

**Comment by WSSLidl** [comment]
Gotcha, done!
Also re-added LS docks ones, cause the army mapping is off now.
