### ISSUE TITLE
Ammunation marker accessible at their roof

### ISSUE THREAD

**Issue by WSS-tracking** [WSS-tracking/WSS#18]
![afbeelding](https://user-images.githubusercontent.com/70011829/91426373-ba646b80-e85c-11ea-9def-259170b4052f.png)

**Comment by dev-bas** [comment]
It also is poppin up when flying over it... Resulting in the effect shown in the image below.

![afbeelding](https://user-images.githubusercontent.com/70659371/92326430-6f173d80-f052-11ea-9d0e-ba7c48f9a8c7.png)

**Comment by WSSLidl** [comment]
Replaced ANAL ammunations with a new ammunation :) Credits to Wizard for developing it back in the NL days <3
