### ISSUE TITLE
RC Warehouse worker spawn is awfull far from the actual mission area. 

### ISSUE THREAD

**Issue by WSS-tracking** [WSS-tracking/WSS#21]
![afbeelding](https://user-images.githubusercontent.com/70011829/91466212-1516bb00-e88f-11ea-8ef7-e54e1c0d8015.png)

**Comment by WSS-tracking** [comment]
There also isn't anything at the three dots.

**Comment by WSSLidl** [comment]
Removed spawn, don't think there's a warehouse job in RC.
