### ISSUE TITLE
Save Disk Bug [Spawning a car - going into interior before it teleports you into your car]

### ISSUE THREAD

**Issue by Julian421** [WSS-tracking/WSS#35]
If you spawn a car from a disk, and run inside an interior, before you get teleported inside your car, you end up in a glitched dimension. Reconnecting doesn't help, "F1 > I'm Stuck" or warp from an admin helps though.

![unknown](https://user-images.githubusercontent.com/70525581/91727903-a2655280-eba2-11ea-8c86-a3c88ea3facf.png)

**Comment by WSSLidl** [comment]
Fixed this by freezing the player when a car is spawned. No you can't cancel it, think before you spawn :)
