### ISSUE TITLE
[TT]Cappo reported he is unable to stop a turf war after he started it

### ISSUE THREAD

**Issue by WSS-tracking** [WSS-tracking/WSS#36]

**Comment by dev-bas** [comment]
I've tested it and I can confirm /stopwar does not stop it. Also doing /turf to disable the turf view does not work as well. 

It does remove the zones from the map, but the turfing keeps going on. This is also shown on the screenshot below. 

A workaround is to just leave the zone and let the turf reset itself. 

![afbeelding](https://user-images.githubusercontent.com/70659371/92027703-367e1800-ed63-11ea-87c6-37f649a7c980.png)

**Comment by WSSLidl** [comment]
There is no command to stop turfing, why would you even wanna stop turfing and stay in the area???

Leaving the turf area will stop the war
