### ISSUE TITLE
Army vs terrorist suggestion made by xAkShadow

### ISSUE THREAD

**Issue by dev-bas** [WSS-tracking/WSS#39]
This suggestion is made by xAkShadow on the 2nd of September 2020 through discord.

First one is some kind of Army vs Terrorism, each with their spawns opened to public with some amount of rank tiers. The player only being able to pick one at one time only.

* Have dedicated turf areas on BC/TR only for these 2, which you earn some amount of money by doing so and maybe higher payouts when the rank is higher.
* Reward this 2 for killing eachother with a small amount of amount of money and maybe just like turfs the higher the rank the higher the payout.
* Each player would start at a low rank and earn higher ranks with the amount of kills that they got when spawned as the role. The kills would also count against other classes and not only between these 2.
* Army could also help the police/squads with controlling the activities but not be able to arrest. The terrorists would be able to help crims but not being able to do activities like HR. 
* I would also recommend to maybe keep the same weapons for each rank but just maybe change payouts or some aditional stuff like no blip.

**Comment by WSSLidl** [comment]
We've gone with a cop and criminal group for now. We'll take these suggestions with us in developing these groups. Thx!
