### ISSUE TITLE
Registration bug with password length

### ISSUE THREAD

**Issue by WSS-tracking** [WSS-tracking/WSS#4]
Issue created after the bug report of Reket on 19-08-2020

if you register with a password which is shorter than required, it will say the alert but will never actually cancel the registering and via /register, so every time you would log in it would still let you in but would welcome you with this message: login: Invalid password for account ACCOUNTNAME. This will also bug your hours played, keeping them at N/A. I had around 40 hours of playtime before, and it displayed it as N/A, and now when I tried to /login with the password I used which was too short after logging in through the login panel, and now it says 00:00.

**Comment by WSSLidl** [comment]
Fixed a while ago
