### ISSUE TITLE
Sometimes a turf resets itself with no rivals defending

### ISSUE THREAD

**Issue by dev-bas** [WSS-tracking/WSS#54]
It looks like Thuga Thugs defended against themselves in the Rebels turf. It resetted without Rebels around

![afbeelding](https://user-images.githubusercontent.com/70659371/92311801-aafec400-efba-11ea-927c-786b0af805d4.png)
![afbeelding](https://user-images.githubusercontent.com/70659371/92311908-d930d380-efbb-11ea-97f0-6ad1dbcf124a.png)

**Comment by WSSLidl** [comment]
Not a bug, your teammate is in the vehicle which prevents the percentage from going up.
However, since more people have complained about this. I've adjusted the script so that it only counts the players who are outside the vehicle as attackers.
