### ISSUE TITLE
Trucker Marker.

### ISSUE THREAD

**Issue by FekkOffItsHamppe** [WSS-tracking/WSS#63]
The trucker marker is under the bridge, and when you drive on the bridge. The delivery select is popping up. Just move the marker a little bit and it wont be a problem. 

(LS DOCKS)
![](https://i.imgur.com/5Ce5ls0.png)

**Comment by WSS-tracking** [comment]
![image](https://user-images.githubusercontent.com/70011829/92626653-7e082500-f2ca-11ea-87be-fcf15315ddcc.png)

**Comment by dev-bas** [comment]
I've repositioned the marker. Thanks for reporting it !
