### ISSUE TITLE
New text above head mechanic also displays “hidden” teamchat 

### ISSUE THREAD

**Issue by Liyones** [WSS-tracking/WSS#80]
When u type in gang chat it works perfectly and it doesn't show the text u wrote, and also in local chat and main chat it works, but the problem is in team chat when u type something the peoples near u can see it also not from ur team and it can leak BRs , so I suggest to remove that text at all and never show text up to skin because it's useless.

**Comment by Liyones** [comment]
bump , (just to post it in discord ithub channel)

**Comment by WSSLidl** [comment]
chaticon is turned off
