### ISSUE TITLE
Reward addicted players for their time in game

### ISSUE THREAD

**Issue by dev-bas** [WSS-tracking/WSS#91]
As requested by Woytex through discord on the 17th of September 2020 

I would like to add some online time rewards tho, I think that would give players some way of "addiction" to the server, like ranks and with ranks like maybe access to a vehicle or maybe like you gotta have like X hours to lead an "official gang/squad" but yeah AFking is something I didn't really think much about

**Comment by WSSLidl** [comment]
We tried level systems in ANAL, didn't work out great because people want access to everything the moment they join. However, we'll see what we can do with this suggestion
